//! Custom-validator token generation.
//!
//! A custom validation function receives a borrowed field value and returns
//! `Result<(), E>`, where `E` implements `ToString`.
//!
//! For an `Option<T>` field, the custom validator receives `&T` and runs only
//! when the field contains `Some(value)`. The surrounding optional-field block
//! is generated by the validation coordinator.

use quote::quote;
use syn::{LitStr, Type};

use super::super::args::{BuiltChecks, ValidateArgs};

/// Appends a configured custom-validator invocation.
///
/// The declared field type is used for ordinary fields. For `Option<T>`, the
/// supplied `opt_inner` type is used so the validator receives `&T`.
pub fn build_custom_check(
    built_checks: &mut BuiltChecks,
    validate_args: &ValidateArgs,
    field_ty: &Type,
    opt_inner: Option<&Type>,
    field_name_lit: &LitStr,
) {
    let Some(custom_path) = &validate_args.custom else {
        return;
    };

    let validated_ty = opt_inner.unwrap_or(field_ty);

    built_checks.field_rules_val.push(quote! {
        {
            let __oximod_val: &#validated_ty = val;

            if let Err(error) = #custom_path(__oximod_val) {
                validation_errors.push(
                    ::oximod::ValidationError::new(
                        #field_name_lit,
                        error.to_string(),
                    ),
                );
            }
        }
    });
}

#[cfg(test)]
mod tests {
    use proc_macro2::Span;
    use quote::{ToTokens, quote};
    use syn::{LitStr, Type, parse_quote};

    use crate::validate::args::{BuiltChecks, ValidateArgs};

    use super::build_custom_check;

    #[test]
    fn absent_custom_validator_generates_no_check() {
        let mut built_checks = BuiltChecks::default();
        let validate_args = ValidateArgs::default();
        let field_ty: Type = parse_quote!(String);

        let field_name = LitStr::new("name", Span::call_site());

        build_custom_check(
            &mut built_checks,
            &validate_args,
            &field_ty,
            None,
            &field_name,
        );

        assert!(
            built_checks.field_rules_val.is_empty(),
            "fields without a custom validator should generate no check"
        );
    }

    #[test]
    fn ordinary_fields_use_their_declared_type() {
        let mut built_checks = BuiltChecks::default();

        let validate_args = ValidateArgs {
            custom: Some(parse_quote!(validators::validate_name)),
            ..Default::default()
        };

        let field_ty: Type = parse_quote!(String);

        let field_name = LitStr::new("name", Span::call_site());

        build_custom_check(
            &mut built_checks,
            &validate_args,
            &field_ty,
            None,
            &field_name,
        );

        assert_eq!(built_checks.field_rules_val.len(), 1);

        let generated = compact(&built_checks.field_rules_val[0]);

        assert!(
            generated.contains("let__oximod_val:&String=val;"),
            "custom validator should receive the declared field type: \
             {generated}"
        );

        assert!(
            generated.contains("validators::validate_name(__oximod_val)"),
            "configured validator path should be invoked: \
             {generated}"
        );

        assert!(
            generated.contains(
                "::oximod::ValidationError::new(\
\"name\",error.to_string(),)"
            ),
            "validator errors should retain the field name: \
             {generated}"
        );
    }

    #[test]
    fn optional_fields_use_their_inner_type() {
        let mut built_checks = BuiltChecks::default();

        let validate_args = ValidateArgs {
            custom: Some(parse_quote!(validators::validate_nickname)),
            ..Default::default()
        };

        let field_ty: Type = parse_quote!(Option<String>);

        let inner_ty: Type = parse_quote!(String);

        let field_name = LitStr::new("nickname", Span::call_site());

        build_custom_check(
            &mut built_checks,
            &validate_args,
            &field_ty,
            Some(&inner_ty),
            &field_name,
        );

        assert_eq!(built_checks.field_rules_val.len(), 1);

        let generated = compact(&built_checks.field_rules_val[0]);

        assert!(
            generated.contains("let__oximod_val:&String=val;"),
            "optional custom validators should receive the inner type: \
             {generated}"
        );

        assert!(
            !generated.contains("&Option<String>"),
            "optional custom validators should not receive Option<T>: \
             {generated}"
        );
    }

    #[test]
    fn custom_check_is_appended_after_existing_rules() {
        let existing = quote! {
            existing_check();
        };

        let mut built_checks = BuiltChecks {
            field_rules_val: vec![existing.clone()],
            ..Default::default()
        };

        let validate_args = ValidateArgs {
            custom: Some(parse_quote!(validate_value)),
            ..Default::default()
        };

        let field_ty: Type = parse_quote!(u32);

        let field_name = LitStr::new("value", Span::call_site());

        build_custom_check(
            &mut built_checks,
            &validate_args,
            &field_ty,
            None,
            &field_name,
        );

        assert_eq!(built_checks.field_rules_val.len(), 2);

        assert_eq!(
            compact(&built_checks.field_rules_val[0]),
            compact(&existing),
            "existing validation rules should remain unchanged"
        );

        assert!(
            compact(&built_checks.field_rules_val[1]).contains("validate_value(__oximod_val)"),
            "custom check should be appended after existing rules"
        );
    }

    fn compact(tokens: &impl ToTokens) -> String {
        tokens.to_token_stream().to_string().replace(' ', "")
    }
}
