[package]
name = "oximod_core"
version = "0.2.0"
edition = "2024"
authors = ["Arshia Eskandari <email@arshiaeskandari.com>"]
description = "The core logic and error handling for OxiMod, a MongoDB ODM for Rust."
license = "MIT"
repository = "https://github.com/arshia-eskandari/oximod"
readme = "README.md"
keywords = ["mongodb", "odm", "mongoose", "rust"]
categories = ["database", "asynchronous"]

[dependencies]
async-trait = "0.1.89"
mongodb = "3.5.1"
thiserror = "2.0.18"
serde = "1.0.228"

[features]
# enables diagnostics in release builds
debug-print = []
